# Generated by Django 5.0 on 2024-01-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_ordermain_order_user_ordermain_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='order_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_state_province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_zip_postal_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
